# This workflow will do a clean install of node dependencies, cache/restore them, build the source code, use linter to check the code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, lint and test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-lint-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'yarn'
        
    - name: Yarn install
      run: yarn install
      
    - name: Yarn build
      run: yarn build
    
    - name: Yarn lint
      run: yarn lint

    - name: Run component tests
      run: yarn component-test:ci
      
    - name: Run E2E tests
      run: yarn test:ci